# Generated by Django 5.1.1 on 2024-09-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_quanity_productentry_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductEntry',
            new_name='Product',
        ),
    ]
